'use client';
import { useState } from 'react';
import { Card, Badge } from '@/components/Card';
export default function PhotosPage() {
  const [fileName, setFileName] = useState('');
  const [consent, setConsent] = useState(false);
  const [analyzed, setAnalyzed] = useState(false);
  return <div className="space-y-6"><section><Badge>Photo Search</Badge><h1 className="mt-4 font-serif text-5xl">Upload inspiration. Price the look.</h1><p className="mt-3 max-w-3xl text-charcoal/70">Upload a dress, shoe, flower arrangement, chandelier, tablescape, venue, or decor item. We’ll help estimate what it may cost and show similar option cards without pretending a retail item equals full wedding execution.</p></section><Card><h2 className="font-serif text-3xl">Upload inspiration</h2><input data-testid="photo-input" type="file" accept="image/*" onChange={e=>setFileName(e.target.files?.[0]?.name || '')} className="mt-4 block w-full rounded-2xl border border-dashed border-charcoal/20 bg-white p-8" />{fileName && <p className="mt-3 font-semibold">Selected: {fileName}</p>}<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm"><strong>Photo analysis notice:</strong> To analyze this photo, the image may be sent to a third-party visual search or product search provider. Do not upload private, sensitive, explicit, copyrighted, confidential, or identifying images unless you are comfortable using this feature. Results are estimates only and may be wrong.</div><label className="mt-4 flex gap-2 text-sm"><input data-testid="photo-consent" type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} /> I understand and want to analyze this photo.</label><button data-testid="analyze-photo" disabled={!fileName || !consent} onClick={()=>setAnalyzed(true)} className="mt-4 rounded-full bg-charcoal px-6 py-3 font-bold text-linen disabled:opacity-40">Analyze this photo</button></Card>{analyzed && <Card data-testid="photo-results"><Badge>Contract-ready result</Badge><h2 className="mt-3 font-serif text-3xl">Detected item: crystal chandelier-style reception lighting</h2><p className="mt-2 text-charcoal/70">Provider posture: seeded + contract-ready. No fake live vendor/product search is claimed.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{['Closest Match','Cheapest Similar','Best Value'].map((label,i)=><Card key={label} className="shadow-none"><h3 className="font-serif text-2xl">{label}</h3><p className="mt-2 text-sm">Retailer option placeholder</p><p className="mt-2 font-bold">Displayed price: ${[249,119,189][i]}</p><p className="mt-3 text-sm"><strong>Retail item price:</strong> ${[249,119,189][i]}</p><p className="text-sm"><strong>Wedding execution estimate:</strong> $800–$3,500</p><p className="mt-2 text-xs text-charcoal/60">Price/availability verification required. Installation, venue approval, labor, power, rigging, teardown, insurance, and safety are separate.</p><button className="mt-4 rounded-full bg-white px-4 py-2 text-sm font-bold">Add to dashboard</button></Card>)}</div></Card>}</div>;
}
