import { seoMetadata } from '@/lib/seo';
import { PARENT_HOST } from '@/lib/site-config';
import Image from 'next/image'; import {suite,products} from '@/lib/products'; import {CheckoutButton} from '@/components/CheckoutButton';
export const metadata = seoMetadata({
  title: 'Dream Wedding Operations Suite',
  description: 'All four wedding execution tools in one purchase: checklist, budget, timeline, and seating chart, plus shared vendor, payment, and wedding-week handoff files.',
  host: PARENT_HOST,
  path: '/products/operations-suite'
});
export default function SuitePage(){return <div className="space-y-14 pb-20"><section className="grid overflow-hidden rounded-[2rem] bg-charcoal text-linen lg:grid-cols-2"><div className="p-8 md:p-12"><p className="text-xs font-bold uppercase tracking-[.25em] text-linen/55">Complete planning system</p><h1 className="mt-3 font-serif text-6xl">All four execution tools. One connected suite.</h1><p className="mt-5 text-lg text-linen/75">${suite.standalone_value} separately. ${suite.price} together. Save ${suite.savings} with one protected purchase.</p><div className="mt-7"><CheckoutButton sku={suite.sku} price={suite.price} label={`Get the complete suite — $${suite.price}`}/></div></div><div className="relative min-h-[440px]"><Image src={suite.image} alt="Dream Wedding Operations Suite with all four planning products" fill priority className="object-cover"/></div></section><section><h2 className="font-serif text-5xl">Everything included</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{products.map(p=><article className="rounded-[1.5rem] bg-white p-6" key={p.id}><h3 className="font-serif text-3xl">{p.name}</h3><p className="mt-3 text-sm text-charcoal/65">{p.promise}</p><p className="mt-4 font-bold">Standalone value: ${p.price}</p></article>)}</div></section><section className="rounded-[2rem] bg-linen p-8"><h2 className="font-serif text-5xl">Buy once. Keep the current release.</h2><p className="mt-4 max-w-3xl text-lg text-charcoal/70">The suite includes editable and printable files, release manifests, personal-use licensing, and support through info@weddingchecklistpdf.com.</p><div className="mt-6"><CheckoutButton sku={suite.sku} price={suite.price}/></div></section></div>}
