'use client';
import { useState } from 'react';
export default function TrendSubmitForm() {
  const [status, setStatus] = useState('');
  async function submit(formData: FormData) {
    setStatus('Submitting...');
    const body = Object.fromEntries(formData.entries());
    const res = await fetch('/api/submit-trend', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });
    setStatus(res.ok ? 'Thank you — we received your idea. Our team may review it before adding it to the Trend Concierge.' : 'We could not submit your idea right now. Please try again later.');
  }
  return <form action={submit} className="mt-5 grid gap-3" data-testid="trend-submit-form"><input className="hidden" name="company" tabIndex={-1} autoComplete="off" /><div className="grid gap-3 md:grid-cols-2"><input required name="idea_name" maxLength={120} placeholder="Trend / idea name" className="rounded-2xl border border-charcoal/10 p-3" /><select name="category" className="rounded-2xl border border-charcoal/10 p-3"><option>Guest Experience</option><option>Ceremony</option><option>Reception</option><option>Fashion</option><option>Flowers</option><option>Decor</option><option>Food + Drink</option><option>Destination</option><option>Luxury</option><option>Quirky</option></select></div><textarea required name="description" maxLength={1000} placeholder="What is it?" className="min-h-28 rounded-2xl border border-charcoal/10 p-3" /><div className="grid gap-3 md:grid-cols-3"><select name="source_type" className="rounded-2xl border border-charcoal/10 p-3"><option>TikTok</option><option>Instagram</option><option>Pinterest</option><option>Wedding I attended</option><option>Planner</option><option>Venue</option><option>Other</option></select><input name="source_url" maxLength={500} placeholder="Link, if you have one" className="rounded-2xl border border-charcoal/10 p-3" /><select name="budget_feel" className="rounded-2xl border border-charcoal/10 p-3"><option>No idea</option><option>Cheap</option><option>Affordable</option><option>Standard</option><option>Luxury</option><option>Ultra Luxe</option></select></div><textarea name="why_cool" maxLength={750} placeholder="Why is it cool?" className="min-h-24 rounded-2xl border border-charcoal/10 p-3" /><label className="flex gap-2 text-sm"><input type="checkbox" name="price_this_out" /> Should we price this out?</label><p className="text-xs text-charcoal/60">Please do not submit private information, copyrighted text, confidential vendor quotes, personal contact details, or anything you do not have permission to share.</p><button className="rounded-full bg-charcoal px-6 py-3 font-bold text-linen">Submit idea</button>{status && <p data-testid="trend-submit-status" className="rounded-2xl bg-ivory p-3 text-sm">{status}</p>}</form>;
}
