import Image from 'next/image';
import Link from 'next/link';
import { ProductCard } from '@/components/ProductCard';
import { CheckoutButton } from '@/components/CheckoutButton';
import { products, suite, supportEmail } from '@/lib/products';

const trust = [
  ['Instant protected delivery','Verified purchases receive access on the success page and by email.'],
  ['Real working files','Every product includes editable, printable, vendor-ready files—not a decorative one-page PDF.'],
  ['One-time purchase','Pay once. Keep the current release for personal use. No subscription.'],
  ['Human support',`Order and access help goes to ${supportEmail}.`]
];

export default function HomePage(){return <div className="space-y-20">
<section className="overflow-hidden rounded-[2.25rem] border border-charcoal/10 bg-linen shadow-soft"><div className="grid gap-8 p-6 md:p-10 lg:grid-cols-[.9fr_1.1fr] lg:p-12"><div className="self-center"><p className="text-xs font-bold uppercase tracking-[.28em] text-charcoal/50">Four paid tools. One free planning foundation.</p><h1 className="mt-4 font-serif text-6xl leading-[.96] md:text-7xl">Plan every detail. Stay on budget. Enjoy the day.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-charcoal/70">Use Dream Wedding Builder free. Then buy the exact execution tool you need for seating, budget, timeline, or your planning checklist.</p><div className="mt-7 flex flex-wrap gap-3"><Link className="rounded-full bg-charcoal px-6 py-4 font-bold text-linen" href="/build">Build my wedding free</Link><Link className="rounded-full border border-charcoal/20 bg-white px-6 py-4 font-bold" href="/shop">Shop all wedding tools — save with the suite</Link></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm text-charcoal/65"><span>✓ One-time payment</span><span>✓ Editable files</span><span>✓ Instant protected access</span><span>✓ Use forever</span></div></div><div className="relative min-h-[420px] overflow-hidden rounded-[1.75rem] bg-white"><Image src="/product-images/operations-suite.webp" alt="Dream Wedding Operations Suite preview showing all four wedding planning products" fill priority sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div></div></section>
<section><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Choose the tool you need most</p><h2 className="mt-3 font-serif text-5xl md:text-6xl">Four high-stress wedding jobs. Four finished solutions.</h2><p className="mt-4 text-lg leading-8 text-charcoal/65">Every card shows the price before you click. Every product page shows the files, outcome, delivery process, and limitations before checkout.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="overflow-hidden rounded-[2rem] bg-charcoal text-linen"><div className="grid lg:grid-cols-2"><div className="p-7 md:p-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-linen/55">Best value</p><h2 className="mt-3 font-serif text-5xl">All four tools for ${suite.price}</h2><p className="mt-4 text-lg leading-8 text-linen/75">${suite.standalone_value} if purchased separately. Save ${suite.savings} and keep every file in one connected planning system.</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{suite.features.map(f=><li className="text-sm font-semibold" key={f}>✓ {f}</li>)}</ul><div className="mt-7"><CheckoutButton sku={suite.sku} price={suite.price} label={`Get the complete suite — $${suite.price}`}/></div></div><div className="relative min-h-[420px]"><Image src={suite.image} alt="Complete Dream Wedding Operations Suite product preview" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div></div></section>
<section><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Why couples pay for these tools</p><h2 className="mt-3 font-serif text-5xl">Free inspiration is easy. Final-mile execution is not.</h2><p className="mt-4 text-lg leading-8 text-charcoal/65">These products are built around the handoffs and mistakes that create expensive wedding-week stress: unassigned guests, hidden balances, missing owners, impossible timing, and generic task lists.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{trust.map(([h,b])=><article className="rounded-[1.5rem] bg-linen p-6" key={h}><h3 className="font-serif text-3xl">{h}</h3><p className="mt-3 text-sm leading-6 text-charcoal/65">{b}</p></article>)}</div></section>
<section className="grid gap-8 rounded-[2rem] border border-charcoal/10 bg-white p-7 md:p-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">How it works</p><h2 className="mt-3 font-serif text-5xl">From purchase to usable handoff in four steps.</h2></div><ol className="space-y-4 text-charcoal/70"><li><strong>1. Choose your tool:</strong> Buy one product or the complete suite.</li><li><strong>2. Pay securely:</strong> Checkout is handled through Stripe.</li><li><strong>3. Receive access:</strong> Verified purchases unlock protected files on screen and by email.</li><li><strong>4. Customize and hand off:</strong> Use the editable files with your partner, venue, vendors, or coordinator.</li></ol></section>
<section className="rounded-[2rem] bg-rose/20 p-7 text-center md:p-12"><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Not sure which tool to buy?</p><h2 className="mt-3 font-serif text-5xl md:text-6xl">Start with the free Builder. It will show you where the plan is weakest.</h2><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/build" className="rounded-full bg-charcoal px-7 py-4 font-bold text-linen">Build my wedding free</Link><Link href="/shop" className="rounded-full border border-charcoal/20 bg-white px-7 py-4 font-bold">Compare paid tools and prices</Link></div></section>
</div>}
