#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
const root=process.cwd();
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>{const f=path.join(root,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n');};
const idx=read('data/authority_scale/fanout_100k/index.json');
const gov=read('data/authority_scale/velocity_governor.json');
const doc=read('data/authority/content_registry.json');
const existingSlugs=new Set(doc.pages.map(p=>p.slug));
const existingTitles=new Set(doc.pages.map(p=>String(p.title||'').trim().toLowerCase()));
const ledgerPath='data/authority_scale/publication_ledger.json';
const ledger=fs.existsSync(path.join(root,ledgerPath))?read(ledgerPath):{schema_version:'1.1',published_ids:[],runs:[]};
const used=new Set(ledger.published_ids||[]);
const today=new Date().toISOString().slice(0,10);
const alreadyToday=(ledger.runs||[]).filter(r=>String(r.run_at||'').startsWith(today)).reduce((n,r)=>n+Number(r.created||0),0);
const dailyCeiling=Number(gov.current_default_new_page_ceiling_per_day||15);
const remaining=Math.max(0,dailyCeiling-alreadyToday);
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
const titleCase=s=>String(s).replace(/\b\w/g,c=>c.toUpperCase());
const productFor=t=>t.includes('seat')?'seating-chart-maker':t.includes('budget')||t.includes('payment')?'budget-spreadsheet':t.includes('timeline')||t.includes('schedule')||t.includes('run of show')?'timeline-template':t.includes('checklist')||t.includes('emergency')?'checklist-pdf':'operations-suite';
const allowedIntents=new Set(['how to plan {topic}','{topic} checklist','{topic} decision guide','{topic} step by step','how to organize {topic}','how to simplify {topic}','{topic} workflow','{topic} framework','{topic} FAQ']);
function topicProfile(topic){
  const t=String(topic).toLowerCase();
  const profiles=[
    [/seating chart|seating conflicts/,{focus:'table capacity, relationship dynamics, accessibility, and a stable seat-assignment version',inputs:['final-ish guest attendance','table shapes and capacities','household or relationship constraints','mobility and accessibility needs'],pitfalls:['splitting linked households without intent','placing high-conflict guests together','changing table capacities after assignments are built']}],
    [/budget|payment schedule|tradeoffs/,{focus:'a hard spending ceiling, committed-versus-estimated costs, payment timing, and an explicit contingency reserve',inputs:['total spending ceiling','signed commitments and deposits','remaining estimates','payment due dates'],pitfalls:['counting estimates as final costs','forgetting taxes, fees, gratuities, or delivery charges','committing deposits before tradeoffs are visible']}],
    [/timeline|run of show/,{focus:'backward planning from immovable event times with realistic buffers and handoff owners',inputs:['ceremony and reception start times','vendor arrival and setup windows','travel and transition time','photo and meal timing'],pitfalls:['building the day with no transition buffer','letting vendors hold conflicting timelines','changing one event without updating downstream handoffs']}],
    [/checklist|emergency kit/,{focus:'a single status-controlled list that distinguishes done, blocked, waiting, and not-applicable work',inputs:['required decisions','owner for each item','due date','blocking dependency'],pitfalls:['using multiple conflicting checklists','marking waiting items as complete','keeping tasks that no longer apply']}],
    [/venue/,{focus:'capacity, access, restrictions, weather fallback, vendor rules, and total logistical fit before aesthetics',inputs:['guest-count range','indoor and outdoor capacity','accessibility and load-in rules','curfew, noise, catering, and vendor restrictions'],pitfalls:['choosing for appearance before capacity and access are proven','assuming rain backup is equivalent to the primary plan','missing exclusive-vendor or timing restrictions']}],
    [/guest list|guest experience/,{focus:'a controlled headcount model tied to capacity, budget, household rules, and invitation priority',inputs:['maximum capacity','per-guest cost pressure','household and plus-one policy','priority tiers'],pitfalls:['inviting before the capacity ceiling is real','using inconsistent plus-one rules','failing to track declines before filling open capacity']}],
    [/vendor selection|vendor handoff|contracts/,{focus:'scope clarity, availability, contract terms, dependencies, and handoff ownership across vendors',inputs:['required scope','availability','written deliverables','payment and cancellation terms'],pitfalls:['comparing vendors on price without scope parity','relying on verbal promises not reflected in the contract','leaving cross-vendor handoffs ownerless']}],
    [/day logistics|day-of coordination|transportation/,{focus:'movement of people, materials, vendors, and information through timed handoffs',inputs:['arrival and departure windows','load-in and parking constraints','transport routes','named handoff owners'],pitfalls:['assuming travel time is zero','leaving setup dependencies between vendors undefined','having no escalation owner for late arrivals']}],
    [/ceremony/,{focus:'the legal, cultural, accessibility, processional, and timing requirements that define the ceremony sequence',inputs:['officiant requirements','ceremony order','processional participants','accessibility and language needs'],pitfalls:['treating ceremonial requirements as decor choices','forgetting document or officiant deadlines','changing the processional without updating cues and seating']}],
    [/reception/,{focus:'guest flow across arrival, seating, food, speeches, entertainment, and departure without bottlenecks',inputs:['room layout','meal service plan','speech and entertainment sequence','guest movement and accessibility'],pitfalls:['stacking speeches and service in conflicting windows','creating dead zones between major moments','ignoring how guests move between spaces']}],
    [/destination|lodging blocks|hotel/,{focus:'travel, lodging, local logistics, communication deadlines, and contingency planning for guests away from home',inputs:['travel window','lodging inventory','ground transportation','local venue and vendor constraints'],pitfalls:['assuming guests will infer travel logistics','holding too little lodging inventory','publishing plans before local constraints are confirmed']}],
    [/micro wedding|small wedding/,{focus:'protecting the highest-value guest experience while deliberately limiting headcount, vendor count, and production complexity',inputs:['guest ceiling','must-have shared moments','space and meal format','minimum vendor support'],pitfalls:['rebuilding a large-wedding production at smaller headcount','adding complexity that does not improve the guest experience','spending the saved headcount budget without reprioritizing']}],
    [/elopement/,{focus:'legal readiness, ceremony essentials, travel logistics, witness requirements, and intentional documentation with minimal production overhead',inputs:['marriage-license requirements to verify','officiant and witness plan','travel and ceremony location access','photo or documentation priorities'],pitfalls:['assuming an elopement removes legal requirements','arriving without a weather or access fallback','adding last-minute guests without revisiting permits, transport, or ceremony logistics']}],
    [/diy/,{focus:'time, skill, material, storage, transport, setup, teardown, and fallback capacity for work the couple owns directly',inputs:['build hours available','material cost','storage and transport plan','setup and teardown labor'],pitfalls:['valuing materials but not labor time','creating decor that cannot be transported or installed easily','having no fallback if a DIY item is unfinished']}],
    [/cultural|interfaith|multicultural/,{focus:'explicitly mapping traditions, decision authority, language, timing, and family expectations before combining ceremonies or customs',inputs:['required traditions','who has decision authority','language or translation needs','timing and venue constraints'],pitfalls:['treating a tradition as decorative without understanding its requirements','letting families assume conflicting sequences','failing to explain unfamiliar customs to vendors or guests']}],
    [/accessib|inclusive|dietary/,{focus:'designing access, communication, food, mobility, sensory, and participation needs into the plan before vendors and layouts lock',inputs:['known accommodation needs','venue access details','dietary requirements','communication and sensory considerations'],pitfalls:['asking about accommodations too late','treating accessibility as a special add-on','assuming a venue label guarantees the specific access needed']}],
    [/invitation|RSVP/,{focus:'one authoritative guest-contact and response record with deadlines, household logic, meal needs, and follow-up ownership',inputs:['household list','mail or digital contact data','RSVP deadline','meal and accommodation questions'],pitfalls:['sending invitations from an unclean guest list','tracking responses in multiple places','failing to reconcile household-level and individual responses']}],
    [/meal|cake/,{focus:'headcount, dietary needs, service format, timing, storage, delivery, and venue constraints',inputs:['confirmed headcount range','dietary restrictions','service style','delivery and storage requirements'],pitfalls:['finalizing quantities before RSVP reconciliation','assuming dietary labels are sufficient without vendor confirmation','ignoring service timing in the event flow']}],
    [/photo|video/,{focus:'coverage priorities, shot constraints, timeline access, lighting, and coordination with ceremony and reception flow',inputs:['must-capture moments','coverage hours','location transitions','family or group shot priorities'],pitfalls:['creating a shot list that cannot fit the timeline','forgetting travel and setup time','letting photo priorities conflict with guest flow or meal service']}],
    [/music/,{focus:'music responsibilities, cue timing, equipment, licensing or venue constraints, and backup playback',inputs:['ceremony cues','reception moments','equipment plan','venue sound restrictions'],pitfalls:['leaving cue ownership ambiguous','assuming venue equipment meets every need','having no offline or backup playback path']}],
    [/decor|flower/,{focus:'visual priorities constrained by venue rules, installation time, transport, reuse, teardown, and budget',inputs:['priority visual zones','venue installation rules','setup window','transport and teardown ownership'],pitfalls:['designing pieces that exceed setup time','ignoring venue attachment or flame rules','buying decor before reuse and teardown are planned']}],
    [/attire/,{focus:'selection, fittings, alterations, accessories, transport, weather, and day-of dressing timing',inputs:['order deadlines','fitting schedule','alteration lead time','day-of dressing location'],pitfalls:['ordering against optimistic lead times','scheduling final fitting too early','forgetting transport, steaming, or emergency repair needs']}],
    [/registry/,{focus:'a useful, non-duplicative registry aligned with household needs, price range variety, fulfillment, and communication etiquette',inputs:['actual household needs','price-point mix','fulfillment and shipping preferences','registry communication plan'],pitfalls:['adding items only to increase count','duplicating incompatible versions of the same need','sharing registry details in contexts where etiquette expectations differ']}],
    [/family dynamics|wedding party|planning with family/,{focus:'decision rights, boundaries, communication channels, responsibilities, and escalation paths among people helping plan',inputs:['who decides what','who is contributing money or labor','communication cadence','boundary and escalation rules'],pitfalls:['confusing financial contribution with unlimited decision authority','assigning responsibilities without explicit acceptance','using multiple family members as parallel decision channels']}],
    [/rain plan|contingency/,{focus:'pre-deciding trigger conditions, backup spaces, communication, vendor changes, and timing impacts before disruption occurs',inputs:['weather or disruption trigger','backup location','vendor contingency requirements','guest communication method'],pitfalls:['calling a backup plan "the same" without checking capacity and flow','waiting until the event day to assign decision authority','failing to identify costs or timing changes caused by the fallback']}],
  ];
  for(const [re,p] of profiles) if(re.test(t)) return p;
  return {focus:'a dependency-aware plan with one source of truth, explicit ownership, and decisions sequenced before downstream commitments',inputs:['confirmed constraints','open decisions','owners and deadlines','dependencies'],pitfalls:['starting from preferences before constraints','maintaining conflicting versions','treating assumptions as confirmed facts']};
}
function pageCopy(r){
  const topic=r.topic, audience=r.audience||'engaged couples', modifier=r.modifier||'practical';
  const modifierLabel=String(modifier).replace(/_/g,' '), intent=r.intent_pattern||'', profile=topicProfile(topic);
  const inputs=profile.inputs;
  let angle='planning sequence',steps=[];
  if(intent.includes('checklist')){angle='completion checklist';steps=[`Create the ${topic} checklist around ${inputs[0]} and ${inputs[1]}.`,`Mark each item confirmed, blocked, waiting, or not applicable.`,`Assign an owner and due date to every unfinished item.`,`Before closing the checklist, reconcile ${inputs[2]} and ${inputs[3]||'downstream dependencies'}.`,`Publish one final checklist version and reopen only items affected by a confirmed change.`];}
  else if(intent.includes('decision guide')){angle='decision framework';steps=[`Define the exact ${topic} decision and the constraint that cannot move.`,`Limit the choice set to realistic options using ${inputs[0]} and ${inputs[1]}.`,`Compare tradeoffs against ${inputs[2]} and ${inputs[3]||'downstream dependencies'}.`,`Document the winning tradeoff and who owns the follow-through.`,`State the specific condition that would justify reopening the decision.`];}
  else if(intent.includes('workflow')||intent.includes('organize')){angle='ownership workflow';steps=[`Create one source of truth for ${topic} centered on ${inputs[0]}.`,`Separate confirmed inputs from open questions, especially ${inputs[1]}.`,`Assign ownership for ${inputs[2]} and every dependent handoff.`,`Resolve ${inputs[3]||'the highest-risk dependency'} before downstream work locks.`,`Record changes in the same system so old versions cannot keep circulating.`];}
  else if(intent.includes('framework')){angle='planning framework';steps=[`Define the outcome ${topic} must produce for ${audience}.`,`Map ${inputs.join(', ')} as the controlling inputs.`,`Sequence high-dependency decisions before low-dependency preferences.`,`Run one cross-check against guest experience, accessibility, budget, timing, and vendor handoffs.`,`Lock the accepted version and reopen only the affected decision when a material input changes.`];}
  else if(intent.includes('FAQ')){angle='question-and-answer guide';steps=[`List the questions that determine ${inputs[0]} and ${inputs[1]}.`,`Answer what can be answered from confirmed planning facts.`,`Flag questions that require confirmation of ${inputs[2]} or ${inputs[3]||'external constraints'} instead of guessing.`,`Turn every unresolved question into an owner plus next action.`,`Retire outdated answers when the underlying plan changes.`];}
  else {steps=[`Confirm ${inputs[0]} before making downstream ${topic} commitments.`,`Document ${inputs[1]} in the same source of truth.`,`Resolve or assign ownership for ${inputs[2]}.`,`Stress-test the plan against ${inputs[3]||'the next dependent decision'}.`,`Publish the accepted ${topic} plan and update only the dependencies affected by a real change.`];}
  const answer=`For ${audience}, ${topic} works best as a ${angle} focused on ${profile.focus}. Start with ${inputs[0]}, then make ${inputs[1]} explicit before downstream choices harden. A ${modifierLabel} plan should show who owns the next decision, what evidence makes it final, and which later choices depend on it. Do not treat estimates, preferences, or tentative vendor statements as confirmed facts. This guide provides general wedding-planning support and does not invent local rules, current prices, contract terms, vendor availability, or guaranteed outcomes.`;
  const mistakes=profile.pitfalls.map(x=>x.charAt(0).toUpperCase()+x.slice(1)+'.');
  return {answer,steps,mistakes};
}
let candidates=[];const batchTopics=new Set();const batchQueries=new Set();
if(remaining>0){
  outer: for(const sh of idx.shards){
    const raw=zlib.gunzipSync(fs.readFileSync(path.join(root,sh.path.includes('/')?sh.path:`data/authority_scale/fanout_100k/${sh.path}`))).toString('utf8').trim();
    for(const line of raw?raw.split(/\n/):[]){
      const r=JSON.parse(line);const id=r.opportunity_id||r.id;
      if(r.geography||r.source_required||used.has(id)||!allowedIntents.has(r.intent_pattern))continue;
      const s=slug(r.query);const qKey=String(r.query).trim().toLowerCase();
      if(existingSlugs.has(s)||existingTitles.has(qKey)||batchQueries.has(qKey)||batchTopics.has(r.topic))continue;
      candidates.push({...r,slug:s});batchQueries.add(qKey);batchTopics.add(r.topic);
      if(candidates.length>=remaining)break outer;
    }
  }
}
for(const r of candidates){const copy=pageCopy(r);doc.pages.push({slug:r.slug,title:titleCase(r.query),cluster:titleCase(r.topic),product_id:productFor(r.topic),semantic_key:`${r.topic}|${r.intent_pattern}|${r.audience||''}`,source_opportunity_id:r.opportunity_id||r.id,answer:copy.answer,steps:copy.steps,mistakes:copy.mistakes});existingSlugs.add(r.slug);existingTitles.add(String(r.query).toLowerCase());used.add(r.opportunity_id||r.id);}
doc.generated_at=today;write('data/authority/content_registry.json',doc);ledger.published_ids=[...used];ledger.runs.push({run_at:new Date().toISOString(),date:today,created:candidates.length,ceiling:dailyCeiling,already_published_today_before_run:alreadyToday,remaining_budget_before_run:remaining});write(ledgerPath,ledger);console.log(JSON.stringify({created:candidates.length,daily_ceiling:dailyCeiling,already_today:alreadyToday,remaining_before_run:remaining,total_guides:doc.pages.length,distinct_topics_in_batch:batchTopics.size},null,2));
