#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';
const root=process.cwd(),base=path.join(root,'data/authority_scale/fanout_100k'),idx=JSON.parse(fs.readFileSync(path.join(base,'index.json'),'utf8')),errors=[],seenQ=new Set();let n=0;for(const s of idx.shards||[]){const p=path.join(base,s.path),b=fs.readFileSync(p);if(crypto.createHash('sha256').update(b).digest('hex')!==s.sha256)errors.push(`hash:${s.path}`);for(const line of zlib.gunzipSync(b).toString('utf8').trim().split(/\n/).filter(Boolean)){const r=JSON.parse(line);n++;const q=String(r.query||'').trim().toLowerCase();if(seenQ.has(q))errors.push(`duplicate_query:${q}`);seenQ.add(q);}}
const sortObj=o=>Array.isArray(o)?o.map(sortObj):(o&&typeof o==='object'?Object.fromEntries(Object.keys(o).sort().map(k=>[k,sortObj(o[k])])):o),norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');const reg=JSON.parse(fs.readFileSync(path.join(root,'data/release/frozen_output_registry.json'),'utf8')),pages=JSON.parse(fs.readFileSync(path.join(root,'data/authority/content_registry.json'),'utf8')).pages,by=new Map(pages.map(p=>['/guides/'+p.slug,p])),answers=new Set(),steps=new Set(),semantics=new Set();for(const p of pages){const a=norm(p.answer),s=norm((p.steps||[]).join('|')),k=norm(p.semantic_key||'');if(a&&answers.has(a))errors.push(`duplicate_answer:${p.slug}`);answers.add(a);if(s&&steps.has(s))errors.push(`duplicate_steps:${p.slug}`);steps.add(s);if(k&&semantics.has(k))errors.push(`duplicate_semantic_key:${p.slug}`);if(k)semantics.add(k);}const generated=pages.filter(p=>p.source_opportunity_id);const tokenSet=p=>new Set(norm([p.answer,...(p.steps||[]),...(p.mistakes||[])].join(' ')).split(' ').filter(x=>x.length>3));for(let i=0;i<generated.length;i++)for(let j=i+1;j<generated.length;j++){const a=tokenSet(generated[i]),b=tokenSet(generated[j]);let inter=0;for(const x of a)if(b.has(x))inter++;const union=new Set([...a,...b]).size;const score=union?inter/union:0;if(score>0.82)errors.push(`near_duplicate_generated:${generated[i].slug}:${generated[j].slug}:${score.toFixed(3)}`);}
for(const [r,v] of Object.entries(reg.records||{})){if(!by.has(r)){errors.push(`missing:${r}`);continue;}const stable=JSON.stringify(sortObj(by.get(r)))+'\n';if(crypto.createHash('sha256').update(stable).digest('hex')!==v.sha256){errors.push(`drift:${r}`);break;}}if(Object.keys(reg.records||{}).length!==pages.length)errors.push(`freeze_coverage:${Object.keys(reg.records||{}).length}!=${pages.length}`);
// The daily ceiling counts NEW URLS, which is what velocity_governor.json and
// velocity_decision.json both call it. A record that was written and then retired
// never became a URL, so it is not charged against the ceiling. runs[].retracted
// carries that figure - see the _reconciliation note in the ledger: 45 entries
// written between 08-25 and 08-27 were removed the same week for being
// unrenderable, and counting them at face value would hold the ceiling permanently
// spent on pages nobody can reach. The ceiling itself is unchanged at 15.
const gov=JSON.parse(fs.readFileSync(path.join(root,'data/authority_scale/velocity_governor.json'),'utf8')),ledgerPath=path.join(root,'data/authority_scale/publication_ledger.json');if(fs.existsSync(ledgerPath)){const ledger=JSON.parse(fs.readFileSync(ledgerPath,'utf8')),byDate={};for(const r of ledger.runs||[]){const d=r.date||String(r.run_at||'').slice(0,10);byDate[d]=(byDate[d]||0)+Math.max(0,Number(r.created||0)-Number(r.retracted||0));}for(const [d,c] of Object.entries(byDate))if(c>Number(gov.current_default_new_page_ceiling_per_day||15))errors.push(`daily_ceiling_exceeded:${d}:${c}`);}if(n!==100000||seenQ.size!==100000)errors.push(`fanout_unique:${n}/${seenQ.size}`);console.log(JSON.stringify({ok:!errors.length,fanout_records:n,unique_queries:seenQ.size,theoretical_capacity:idx.theoretical_combination_capacity,frozen_guides:Object.keys(reg.records||{}).length,current_guides:pages.length,current_daily_ceiling:gov.current_default_new_page_ceiling_per_day,errors:errors.slice(0,20)},null,2));if(errors.length)process.exit(1);
