import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
export const root=process.cwd();
export const read=(p,fallback=null)=>{const f=path.join(root,p);if(!fs.existsSync(f)){if(fallback!==null)return fallback;throw new Error(`missing ${p}`)}return JSON.parse(fs.readFileSync(f,'utf8'));};
export const write=(p,v)=>{const f=path.join(root,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n');};
export const now=()=>new Date().toISOString();
export const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
export const idFor=(...parts)=>crypto.createHash('sha256').update(parts.map(norm).join('|')).digest('hex').slice(0,20);
export const daysBetween=(a,b)=>Math.floor((new Date(b)-new Date(a))/86400000);
export const hostOf=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return ''}};
