import Link from 'next/link';
import { seoMetadata } from '@/lib/seo';
import { PARENT_HOST } from '@/lib/site-config';
import Image from 'next/image';
import { ProductCard } from '@/components/ProductCard';
import { CheckoutButton } from '@/components/CheckoutButton';
import { products, suite, supportEmail } from '@/lib/products';
export const metadata = seoMetadata({
  title: 'Wedding Planning Tools',
  description: 'Four one-time-purchase wedding tools: checklist PDF, budget spreadsheet, timeline template, and seating chart maker. Editable files, protected delivery, no subscription.',
  host: PARENT_HOST,
  path: '/shop'
});
export default function ShopPage(){return <div className="space-y-14"><section className="grid gap-8 lg:grid-cols-2"><div className="self-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Paid wedding execution tools</p><h1 className="mt-3 font-serif text-6xl md:text-7xl">Buy the tool that finishes the job.</h1><p className="mt-5 text-lg leading-8 text-charcoal/70">Transparent one-time prices. Real editable files. Protected delivery. No subscription.</p></div><div className="relative min-h-[360px] overflow-hidden rounded-[2rem]"><Image src={suite.image} alt="Dream Wedding Operations Suite preview" fill priority sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div></section><section className="grid gap-5 md:grid-cols-2">{products.map(p=><ProductCard key={p.id} product={p}/>)}</section><section className="rounded-[1.5rem] border border-charcoal/10 bg-white p-6"><h2 className="font-serif text-3xl">Deciding between them?</h2><p className="mt-3 text-base leading-7 text-charcoal/70">Put all four tools in one table with what each is best for, its one-time price, and the suite price beside them.</p><Link href="/shop/compare" className="mt-4 inline-flex font-bold underline underline-offset-4">Compare all four wedding tools side by side →</Link></section><section className="rounded-[2rem] bg-charcoal p-7 text-linen md:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-linen/55">Complete bundle</p><h2 className="mt-3 font-serif text-5xl">{suite.name}</h2><p className="mt-4 text-lg text-linen/75">All four products plus shared vendor, payment, responsibility, and wedding-week handoff files.</p><p className="mt-5 font-serif text-3xl"><span className="text-linen/50 line-through">${suite.standalone_value}</span> ${suite.price}</p><p className="mt-1 text-sm text-linen/65">Save ${suite.savings}. One-time purchase.</p><div className="mt-6"><CheckoutButton sku={suite.sku} price={suite.price} label={`Get the complete suite — $${suite.price}`}/></div></div><ul className="grid gap-3 sm:grid-cols-2">{suite.features.map(x=><li key={x} className="rounded-2xl border border-linen/15 bg-linen/5 p-4 text-sm font-semibold">✓ {x}</li>)}</ul></div></section><section className="grid gap-5 md:grid-cols-3"><article><h2 className="font-serif text-3xl">Delivery</h2><p className="mt-3 text-sm leading-6 text-charcoal/65">Verified payments receive protected access on the success page and by email.</p></article><article><h2 className="font-serif text-3xl">License</h2><p className="mt-3 text-sm leading-6 text-charcoal/65">Personal-use license. No resale, redistribution, sublicensing, or template repackaging.</p></article><article><h2 className="font-serif text-3xl">Support</h2><p className="mt-3 text-sm leading-6 text-charcoal/65">Order and recovery help: {supportEmail}</p></article></section></div>}
