import Link from 'next/link';
import { headers } from 'next/headers';
import type { Metadata } from 'next';
import { apexHost, canonicalUrl, guidesForHost, isCanonicalHost, PARENT_HOST, productForHost } from '@/lib/site-config';
import { seoMetadata } from '@/lib/seo';

async function resolvedHost() { const h = await headers(); const host = apexHost(h.get('x-forwarded-host') ?? h.get('host')); return isCanonicalHost(host) ? host : PARENT_HOST; }
export async function generateMetadata(): Promise<Metadata> { const host = await resolvedHost(); const product = productForHost(host); return seoMetadata({ title: `${product?.name ?? 'Wedding Planning'} Guides`, description: `Practical ${product?.name.toLowerCase() ?? 'wedding planning'} guides with working methods, examples, common mistakes, and verification boundaries.`, host, path: '/guides' }); }
export default async function GuidesIndex(){ const host = await resolvedHost(); const product = productForHost(host); const pages = guidesForHost(host); return <div className="mx-auto max-w-6xl space-y-10"><header className="rounded-[2rem] bg-white p-7 shadow-soft md:p-12"><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Practical wedding planning library</p><h1 className="mt-4 font-serif text-6xl md:text-7xl">{product?.name ?? 'Wedding planning'} guides</h1><p className="mt-5 max-w-4xl text-lg leading-8 text-charcoal/70">Every guide is built around a distinct planning decision, working method, example, failure pattern, and verification boundary. The library contains {pages.length} guides owned by this domain.</p></header><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{pages.map((page) => <article key={page.slug} className="flex flex-col rounded-[1.5rem] border border-charcoal/10 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-charcoal/45">{page.cluster}</p><h2 className="mt-3 font-serif text-3xl leading-tight">{page.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-charcoal/65">{page.summary}</p><Link href={`/guides/${page.slug}`} className="mt-5 font-bold underline decoration-charcoal/20 underline-offset-4">Read the guide →</Link></article>)}</div><footer className="text-sm text-charcoal/55">Canonical guide index: {canonicalUrl(host, '/guides')}</footer></div>; }
