import Image from 'next/image';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { products, suite, supportEmail } from '@/lib/products';
import { CheckoutButton } from '@/components/CheckoutButton';
import { StickyPurchaseBar } from '@/components/StickyPurchaseBar';

export function generateStaticParams(){ return products.map(product => ({ slug: product.id })); }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
 const { slug } = await params; const product = products.find(item => item.id === slug); if (!product) notFound();
 const objections = ('objections' in product && product.objections ? product.objections : []) as string[][];
 const outcomes = ('outcomes' in product && product.outcomes ? product.outcomes : []) as string[];
 const audience = ('audience' in product && product.audience ? product.audience : []) as string[];
 const process = ('process' in product && product.process ? product.process : []) as string[];
 const heroImage = 'hero_image' in product ? product.hero_image : ''; const gallery = ('gallery' in product && Array.isArray(product.gallery) ? product.gallery : []) as string[];
 return <div className="space-y-16 pb-24">
 <section className="overflow-hidden rounded-[2.2rem] border border-charcoal/10 bg-linen shadow-soft"><div className="grid lg:grid-cols-[.95fr_1.05fr]"><div className="p-6 md:p-10"><p className="text-xs font-bold uppercase tracking-[.28em] text-charcoal/50">A Dream Wedding Builder product</p><h1 className="mt-4 font-serif text-6xl leading-[.98] md:text-7xl">{product.headline}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-charcoal/70">{'promise' in product ? product.promise : product.sub}</p><div className="mt-6 flex items-end gap-4"><div><p className="font-serif text-5xl">${product.price}</p><p className="text-sm text-charcoal/55">one-time purchase</p></div><p className="pb-1 text-sm text-charcoal/55">Instant protected access after verified payment</p></div><div className="mt-7 flex flex-wrap items-center gap-3"><CheckoutButton sku={product.sku} price={product.price}/><a href="#samples" className="rounded-full border border-charcoal/20 bg-white px-6 py-4 font-bold">View sample pages</a></div><p className="mt-4 text-sm text-charcoal/60">Editable and printable files. Personal-use license. Support: {supportEmail}</p></div><div className="relative min-h-[440px] bg-white">{heroImage && <Image src={heroImage} alt={`${product.name} dashboard and file preview`} fill priority sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/>}</div></div></section>
 <section id="samples" className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-[420px] overflow-hidden rounded-[1.75rem] border border-charcoal/10 bg-white"><Image src={product.image} alt={`${product.name} sample file preview`} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div><aside className="rounded-[1.75rem] bg-white p-7"><p className="text-xs font-bold uppercase tracking-[.22em] text-charcoal/45">Exactly what you receive</p><ul className="mt-5 space-y-3">{product.features.map(feature => <li key={feature} className="rounded-2xl bg-ivory p-4 text-sm font-semibold">✓ {feature}</li>)}</ul><div className="mt-6"><CheckoutButton sku={product.sku} price={product.price} label={`Get ${product.name} — $${product.price}`}/></div></aside></section>
 <section className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">The outcome</p><h2 className="mt-3 font-serif text-5xl">What this product helps you finish</h2><ul className="mt-6 space-y-3">{outcomes.map(x=><li key={x} className="rounded-2xl border border-charcoal/10 bg-white p-4">✓ {x}</li>)}</ul></div><div className="rounded-[1.75rem] bg-linen p-7"><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Best for</p><ul className="mt-5 space-y-3">{audience.map(x=><li key={x} className="border-b border-charcoal/10 pb-3 text-lg">{x}</li>)}</ul><p className="mt-6 text-sm leading-6 text-charcoal/65"><strong>Not sure?</strong> Use the free Dream Wedding Builder first, then return when you know which execution gap is causing the most stress.</p></div></section>
 <section><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">How it works</p><h2 className="mt-3 font-serif text-5xl">From purchase to working handoff</h2><div className="mt-7 grid gap-4 md:grid-cols-5">{process.map((x,i)=><article key={x} className="rounded-[1.5rem] bg-white p-5"><span className="text-xs font-bold text-charcoal/40">0{i+1}</span><p className="mt-3 font-semibold leading-6">{x}</p></article>)}</div><div className="mt-7"><CheckoutButton sku={product.sku} price={product.price} label={`Start with ${product.name} — $${product.price}`}/></div></section>
 <section className="grid gap-8 rounded-[2rem] border border-charcoal/10 bg-white p-7 md:p-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Why not a generic free template?</p><h2 className="mt-3 font-serif text-5xl">Because finishing is different from starting.</h2><p className="mt-4 text-lg leading-8 text-charcoal/70">Free wedding tools are useful for broad planning. This product is built for final-mile execution: complete inputs, reconciliation, ownership, printable and editable handoffs, and product-specific checks.</p></div><div className="grid gap-4"><div className="rounded-2xl bg-ivory p-5"><strong>Generic template</strong><p className="mt-2 text-sm text-charcoal/65">Blank structure, limited guidance, and manual handoff work.</p></div><div className="rounded-2xl bg-linen p-5"><strong>{product.name}</strong><p className="mt-2 text-sm text-charcoal/65">Wedding-specific working files, process guidance, checks, and a defined final output.</p></div></div></section>
 <section><p className="text-xs font-bold uppercase tracking-[.25em] text-charcoal/45">Questions before you buy</p><h2 className="mt-3 font-serif text-5xl">Plain answers, before checkout</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{objections.map(([q,a])=><article key={q} className="rounded-[1.5rem] border border-charcoal/10 bg-white p-6"><h3 className="font-serif text-2xl">{q}</h3><p className="mt-3 text-sm leading-6 text-charcoal/65">{a}</p></article>)}</div><div className="mt-7"><CheckoutButton sku={product.sku} price={product.price} label={`Buy ${product.name} — $${product.price}`}/></div></section>
 <section className="overflow-hidden rounded-[2rem] bg-charcoal text-linen"><div className="grid lg:grid-cols-[1fr_.8fr]"><div className="p-7 md:p-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-linen/60">Best value</p><h2 className="mt-3 font-serif text-5xl">Get all four tools for ${suite.price}</h2><p className="mt-4 max-w-2xl text-linen/75">${suite.standalone_value} separately. Save ${suite.savings} with the Dream Wedding Operations Suite.</p><div className="mt-6"><CheckoutButton sku={suite.sku} price={suite.price} label={`Get the complete suite — $${suite.price}`}/></div><Link href="/shop" className="mt-4 inline-flex font-bold underline underline-offset-4">Compare every product</Link></div><div className="relative min-h-[340px]"><Image src={suite.image} alt="Dream Wedding Operations Suite preview" fill sizes="(max-width:1024px) 100vw, 40vw" className="object-cover"/></div></div></section>
 <section className="rounded-[2rem] border border-charcoal/10 bg-white p-7 md:p-10"><p className="font-semibold">Important boundaries</p><p className="mt-3 text-sm leading-6 text-charcoal/70">These are organizational tools, not legal, financial, safety, accessibility, tax, insurance, or professional-event-planning advice. Verify contracts, costs, timing, capacities, dietary information, accessibility needs, and local requirements with the relevant professionals.</p></section>
 <StickyPurchaseBar name={product.name} sku={product.sku} price={product.price}/>
 </div>;
}
